import type { APIRoute } from 'astro';
import { withBase } from '@/lib/url';

/**
 * robots.txt is generated so the sitemap URL follows the deployment target
 * (`site` + `base` in astro.config.mjs) instead of hardcoding a host.
 */
export const GET: APIRoute = ({ site }) => {
  const sitemap = new URL(withBase('/sitemap-index.xml'), site);

  const body = `# robots.txt for Mantik - FIRST Programming Made Easy
User-agent: *
Allow: /

User-agent: Googlebot
Allow: /

# Sitemap (generated by @astrojs/sitemap)
Sitemap: ${sitemap.href}
`;

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
